#!groovy

// Generated by IBM TransformationAdvisor
// Wed Jan 23 12:01:26 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'sample'
    mvnCommands = '--version'
    test='false'
}